---
- name: create frontend docker image
  hosts: localhost
  tasks:
  - name: run docker command        
    command: sudo docker build -t frontend:0.0.5 .
  - name: run tag command   
    command: sudo docker tag frontend:0.0.5 naveen24788/frontend:0.0.5
  - name: run docker login command  
    command: sudo docker login --username naveen24788 --password Servion@123
  - name: run docker push
    command: sudo docker push naveen24788/frontend:0.0.5