---
- name: create frontend docker image
  hosts: localhost
  tasks:
  - name: run docker command        
    command: docker build -t frontend:{{image_id}} /tmp/devops-s3/dist/
  - name: run tag command   
    command: docker tag frontend:{{image_id}} naveen24788/frontend:{{image_id}}
  - name: run docker login command  
    command: docker login --username naveen24788 --password 46c79302-1968-4a60-af09-65742d5fcf31
  - name: run docker push
    command: docker push naveen24788/frontend:{{image_id}}
